# Automatically generated by twirp_elixir, do not edit manually.
defmodule <%= prefix %>.RPC.Client do
  @moduledoc false

  def call(base_url, pb_mod, service, rpc_name, request) do
    rpc = pb_mod.find_rpc_def(service, rpc_name)
    package_name = pb_mod.get_package_name()
    url = "#{base_url}/twirp/#{package_name}.#{service}/#{rpc_name}"
    request_pb = pb_mod.encode_msg(request, rpc.input)
    headers = [{"content-type", "application/protobuf"}]
    response_pb = post!(url, request_pb, headers)
    pb_mod.decode_msg(response_pb, rpc.output)
  end

  defp post!(url, pb, headers) do
    HTTPoison.post!(url, pb, headers).body
  end
end
