# Automatically generated by twirp_elixir, do not edit manually.
defmodule <%= prefix %>.RPC.<%= service_name %>Server do
  @moduledoc false

  def start_link(options) do
    options
    |> Keyword.put_new(:pb_mod, <%= inspect(pb_mod) %>)
    |> <%= prefix %>.RPC.Server.start_link()
  end

  def child_spec(options) do
    options
    |> Keyword.put_new(:pb_mod, <%= inspect(pb_mod) %>)
    |> <%= prefix %>.RPC.Server.child_spec()
  end
end
