# Automatically generated by twirp_elixir, do not edit manually.
defmodule <%= prefix %>.RPC.<%= service_name %>Client do
  @moduledoc false

  for rpc_name <- <%= inspect(pb_mod) %>.get_rpc_names(<%= inspect(service_name) %>) do
    function_name = Macro.underscore(Atom.to_string(rpc_name)) |> String.to_atom()

    def unquote(function_name)(url, params) do
      <%= prefix %>.RPC.Client.call(url, <%= inspect(pb_mod) %>, <%= inspect(service_name) %>, unquote(rpc_name), params)
    end
  end
end
