# Automatically generated by twirp_elixir, do not edit manually.
defmodule HelloWorld.RPC.HelloWorldClient do
  @moduledoc false

  for rpc_name <- :hello_world_pb.get_rpc_names(:HelloWorld) do
    function_name = Macro.underscore(Atom.to_string(rpc_name)) |> String.to_atom()

    def unquote(function_name)(url, params) do
      HelloWorld.RPC.Client.call(url, :hello_world_pb, :HelloWorld, unquote(rpc_name), params)
    end
  end
end