# Automatically generated by twirp_elixir, do not edit manually.
defmodule HelloWorld.RPC.HelloWorldClient do
  @moduledoc false

  def hello(url, params) do
    HelloWorld.RPC.Client.call(url, :hello_world_pb, :HelloWorld, :Hello, params)
  end
end