# Automatically generated by twirp-elixir, do not edit manually.
defmodule HelloWorld.RPC.HelloWorldServer do
  @moduledoc false

  def start_link(options) do
    options
    |> Keyword.put_new(:pb_mod, :hello_world_pb)
    |> HelloWorld.RPC.Server.start_link()
  end
end
